from easydict import EasyDict as edict

DATA = edict()
DATA.TRAIN = edict()
DATA.TRAIN.DATA_PATH = None
DATA.TRAIN.VALIDATION_SPLIT_RATIO = None
DATA.TRAIN.VALIDATION_SPLIT_RANDOM_STATE = None
DATA.TRAIN.TRAIN_BATCH_SIZE = None
DATA.TRAIN.VAL_BATCH_SIZE = None
DATA.TEST = edict()
DATA.TEST.IMAGE_PATH = None
DATA.TEST.BATCH_SIZE = None

MODEL = None

LOSS = edict()
LOSS.LABEL_SMOOTHING = None

OPTIMIZER = edict()
OPTIMIZER.TYPE = None
OPTIMIZER.MAX_LEARNING_RATE = None
OPTIMIZER.SCHEDULE_GAMMA = None

EPOCHS = edict()
EPOCHS.TOTAL = None
EPOCHS.WARMUP = None

LOGGING = edict()
LOGGING.PATH = None
LOGGING.MODEL_NAME = None
LOGGING.NOTE = None
LOGGING.TRIAL_NUMBER = None
LOGGING.STEPS_PER_LOG = None

